# Generated by Django 5.1.3 on 2025-01-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='skils',
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='skils',
            field=models.ManyToManyField(to='portfolio.skilsmodel'),
        ),
    ]
