# Generated by Django 5.1.3 on 2025-01-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseskilsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('baseskils', models.CharField(max_length=100, verbose_name='baseskils')),
            ],
            options={
                'verbose_name': 'BaseskilsModel',
                'verbose_name_plural': 'BaseskilsModels',
                'db_table': 'baseskils',
            },
        ),
    ]
