# Generated by Django 5.1.3 on 2025-01-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_baseskilsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseskilsmodel',
            old_name='baseskils',
            new_name='baseskils_icon',
        ),
    ]
