# Generated by Django 5.1.3 on 2025-01-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_baseskils_baseskilsmodel_baseskils_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseskilsmodel',
            name='color',
            field=models.CharField(default=1, max_length=100, verbose_name='color'),
            preserve_default=False,
        ),
    ]
