# Generated by Django 5.1.3 on 2025-01-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_baseskilsmodel_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliomodel',
            old_name='decsription',
            new_name='description',
        ),
    ]
